import Link from "next/link";
import {
  ArrowRight,
  BadgeCheck,
  BrainCircuit,
  MessageSquareText,
  ScanSearch,
  Sparkles,
} from "lucide-react";
import { FadeIn, HoverLift, PageTransition } from "@/components/motion-shell";
import { SiteFooter } from "@/components/site-footer";
import { SiteNav } from "@/components/site-nav";

const features = [
  {
    icon: MessageSquareText,
    title: "Interview Question Generator",
    description:
      "Provide your resume and the job description. Get 250 personalized questions across Technical, HR, Projects, Behavioral, and Scenario categories.",
  },
  {
    icon: ScanSearch,
    title: "ATS Score Checker",
    description:
      "Compare your resume against any job description. Get your ATS compatibility score, keyword gaps, missing skills, and improvement recommendations.",
  },
  {
    icon: BrainCircuit,
    title: "Resume ↔ JD Matching",
    description:
      "The AI reads both documents together — matching required skills, keywords, experience, and qualifications from the JD to your resume.",
  },
  {
    icon: BadgeCheck,
    title: "Personalized Answers",
    description:
      "Every question answer is tailored to your actual experience, projects, and skills — not generic templates.",
  },
];

const steps = [
  "Upload your resume PDF or paste the text",
  "Paste the target job description",
  "Get 250 questions + your ATS score",
];

const faqs = [
  [
    "Why do I need to provide a job description?",
    "The AI compares your resume against the JD to generate role-specific questions and an accurate ATS score. Without the JD, the output would be generic rather than tailored to the actual role you're applying for.",
  ],
  [
    "How are the interview questions personalized?",
    "The AI reads your resume to understand your actual skills, projects, and experience level — then reads the JD to understand what the role requires. It generates questions specifically at the intersection of the two.",
  ],
  [
    "What does the ATS score measure?",
    "The ATS report measures keyword alignment, skills match, experience match, education match, and resume formatting strength — all calculated by comparing your resume to the specific job description you provide.",
  ],
  [
    "Can I paste resume text manually?",
    "Yes. If PDF extraction fails or your resume is scanned, a fallback text area lets you paste the content directly.",
  ],
];

export default function Home() {
  return (
    <PageTransition>
      <div className="min-h-screen overflow-hidden text-white">
        <SiteNav />

        <main>
          {/* Hero */}
          <section className="relative mx-auto flex min-h-[calc(100vh-74px)] max-w-7xl flex-col items-center justify-center px-6 py-20 text-center">
            <FadeIn>
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.05] px-4 py-2 text-sm text-zinc-300 backdrop-blur">
                <Sparkles className="size-4 text-violet-300" />
                Resume + Job Description Matching
              </div>
            </FadeIn>

            <FadeIn delay={0.08}>
              <h1 className="mx-auto max-w-4xl text-5xl font-bold leading-tight tracking-tight md:text-7xl">
                HirePilot AI
              </h1>
            </FadeIn>

            <FadeIn delay={0.14}>
              <p className="mx-auto mt-4 max-w-2xl text-base leading-8 text-zinc-400 md:text-lg">
                Upload your resume and paste a job description. Get 250 personalized interview questions and your ATS compatibility score — generated by AI from both documents together.
              </p>
            </FadeIn>

            <FadeIn delay={0.22}>
              <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row">
                <Link
                  href="/register"
                  className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3 font-semibold text-black shadow-2xl shadow-violet-500/20 transition hover:scale-105"
                >
                  Get Started Free <ArrowRight className="size-4" />
                </Link>
                <Link
                  href="/login"
                  className="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/[0.05] px-6 py-3 font-semibold text-white transition hover:bg-white/[0.09]"
                >
                  Sign In
                </Link>
              </div>
            </FadeIn>
          </section>

          {/* Features */}
          <section className="mx-auto max-w-7xl px-6 pb-20">
            <FadeIn>
              <div className="mb-10 max-w-2xl">
                <p className="text-xs font-semibold uppercase tracking-widest text-violet-300">Features</p>
                <h2 className="mt-3 text-3xl font-bold md:text-4xl">
                  Built entirely on Resume ↔ JD matching.
                </h2>
                <p className="mt-3 text-zinc-400">
                  Every feature compares your resume against the job description. No generic outputs.
                </p>
              </div>
            </FadeIn>

            <div className="grid gap-5 md:grid-cols-2">
              {features.map((feature, i) => (
                <FadeIn key={feature.title} delay={i * 0.06}>
                  <HoverLift>
                    <div className="glass-card h-full rounded-2xl p-6">
                      <feature.icon className="size-7 text-violet-300" />
                      <h3 className="mt-4 text-lg font-semibold">{feature.title}</h3>
                      <p className="mt-2 text-sm leading-7 text-zinc-400">{feature.description}</p>
                    </div>
                  </HoverLift>
                </FadeIn>
              ))}
            </div>
          </section>

          {/* How it works */}
          <section className="border-y border-white/10 bg-white/[0.02] px-6 py-20">
            <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.4fr] lg:items-center">
              <FadeIn>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-widest text-blue-300">How it works</p>
                  <h2 className="mt-3 text-3xl font-bold md:text-4xl">
                    From resume + JD to interview-ready.
                  </h2>
                  <p className="mt-3 text-sm leading-7 text-zinc-400">
                    Three steps. Real AI analysis. 250 personalized questions and your ATS score.
                  </p>
                </div>
              </FadeIn>
              <div className="grid gap-4 md:grid-cols-3">
                {steps.map((step, i) => (
                  <FadeIn key={step} delay={i * 0.08}>
                    <div className="glass-card rounded-2xl p-5">
                      <span className="grid size-9 place-items-center rounded-lg bg-gradient-to-br from-blue-500 to-violet-600 text-sm font-bold">
                        {i + 1}
                      </span>
                      <p className="mt-4 text-sm font-medium leading-6">{step}</p>
                    </div>
                  </FadeIn>
                ))}
              </div>
            </div>
          </section>

          {/* What gets generated */}
          <section className="mx-auto max-w-7xl px-6 py-20">
            <FadeIn>
              <div className="mb-10 max-w-2xl">
                <p className="text-xs font-semibold uppercase tracking-widest text-emerald-300">Output</p>
                <h2 className="mt-3 text-3xl font-bold md:text-4xl">250 questions per session.</h2>
                <p className="mt-3 text-sm text-zinc-400">
                  Each question is generated by analyzing both your resume and the job description together.
                </p>
              </div>
            </FadeIn>
            <div className="grid gap-4 sm:grid-cols-5">
              {[
                { label: "Technical", count: 50, desc: "Skill & technology specific", color: "from-blue-500/20 to-violet-500/20 text-blue-200" },
                { label: "HR", count: 50, desc: "Background & culture fit", color: "from-emerald-500/20 to-teal-500/20 text-emerald-200" },
                { label: "Projects", count: 50, desc: "Your actual projects", color: "from-orange-500/20 to-amber-500/20 text-orange-200" },
                { label: "Behavioral", count: 50, desc: "STAR-format scenarios", color: "from-pink-500/20 to-rose-500/20 text-pink-200" },
                { label: "Scenario", count: 50, desc: "Role-based situations", color: "from-violet-500/20 to-indigo-500/20 text-violet-200" },
              ].map((item) => (
                <HoverLift key={item.label}>
                  <div className={`glass-card rounded-2xl p-5 bg-gradient-to-br ${item.color}`}>
                    <p className="text-3xl font-bold">{item.count}</p>
                    <p className="mt-1 font-semibold">{item.label}</p>
                    <p className="mt-1 text-xs opacity-70">{item.desc}</p>
                  </div>
                </HoverLift>
              ))}
            </div>
          </section>

          {/* FAQ */}
          <section className="mx-auto max-w-4xl px-6 pb-20">
            <FadeIn>
              <h2 className="mb-8 text-3xl font-bold">FAQ</h2>
            </FadeIn>
            <div className="grid gap-4">
              {faqs.map(([q, a]) => (
                <div key={q} className="glass-card rounded-2xl p-6">
                  <h3 className="font-semibold">{q}</h3>
                  <p className="mt-3 text-sm leading-7 text-zinc-400">{a}</p>
                </div>
              ))}
            </div>
          </section>

          {/* CTA */}
          <section className="px-6 pb-24">
            <div className="glass-card mx-auto max-w-4xl rounded-3xl p-8 text-center md:p-12">
              <h2 className="text-3xl font-bold md:text-4xl">
                Ready to prepare smarter?
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-zinc-400">
                Upload your resume, paste the job description, and let HirePilot AI generate your complete interview preparation plan.
              </p>
              <Link
                href="/register"
                className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-7 py-3 font-semibold text-black shadow-2xl shadow-violet-500/20 transition hover:scale-[1.03]"
              >
                Start for Free <ArrowRight className="size-4" />
              </Link>
            </div>
          </section>
        </main>

        <SiteFooter />
      </div>
    </PageTransition>
  );
}
