/**
 * download-questions.ts
 * Client-side utility to export interview questions as PDF or DOCX.
 * Supports downloading all sections or a single section.
 */

import type { InterviewResult } from "./career-types";

export type Section = "technical" | "hr" | "projects" | "behavioral" | "scenario";

// ─── Section meta ─────────────────────────────────────────────────────────────

interface SectionMeta {
  key: Section;
  label: string;
  color: [number, number, number]; // RGB
}

const SECTIONS: SectionMeta[] = [
  { key: "technical",  label: "Technical Questions",  color: [99,  102, 241] },
  { key: "hr",         label: "HR Questions",          color: [16,  185, 129] },
  { key: "projects",   label: "Project Questions",     color: [245, 158,  11] },
  { key: "behavioral", label: "Behavioral Questions",  color: [236,  72, 153] },
  { key: "scenario",   label: "Scenario Questions",    color: [139,  92, 246] },
];

// ─── Helpers to normalise questions into a common shape ───────────────────────

interface NormalisedQ {
  index: number;
  question: string;
  answer: string;
  meta?: string; // difficulty / skill / purpose etc.
}

function normalise(result: InterviewResult, section: Section): NormalisedQ[] {
  switch (section) {
    case "technical":
      return result.technicalQuestions.map((q, i) => ({
        index: i + 1,
        question: q.question,
        answer: q.answer,
        meta: [q.difficulty, q.skill, q.topic].filter(Boolean).join(" · "),
      }));
    case "hr":
      return result.hrQuestions.map((q, i) => ({
        index: i + 1,
        question: q.question,
        answer: q.answer,
        meta: q.purpose ? `Purpose: ${q.purpose}` : undefined,
      }));
    case "projects":
      return result.projectQuestions.map((q, i) => ({
        index: i + 1,
        question: q.question,
        answer: q.answer,
        meta: q.difficulty,
      }));
    case "behavioral":
      return result.behavioralQuestions.map((q, i) => ({
        index: i + 1,
        question: q.question,
        answer: q.suggestedAnswer,
        meta: "Suggested Answer",
      }));
    case "scenario":
      return result.scenarioQuestions.map((q, i) => ({
        index: i + 1,
        question: q.question,
        answer: q.suggestedSolution,
        meta: "Suggested Solution",
      }));
  }
}

// ─── PDF ──────────────────────────────────────────────────────────────────────

export async function downloadAsPdf(
  result: InterviewResult,
  section?: Section
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const PAGE_W = 210;
  const PAGE_H = 297;
  const MARGIN = 18;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const LINE_H = 6;

  const sectionsToExport = section
    ? SECTIONS.filter((s) => s.key === section)
    : SECTIONS;

  const totalQuestions = sectionsToExport.reduce((acc, s) => {
    return acc + normalise(result, s.key).length;
  }, 0);

  let isFirstPage = true;

  // ── Cover page ──────────────────────────────────────────────────────────────
  const addCoverPage = (title: string, subtitle: string) => {
    // Dark gradient background simulation via rect
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");

    // Accent line
    doc.setFillColor(99, 102, 241);
    doc.rect(MARGIN, 80, 4, 40, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.text(title, MARGIN + 12, 100);

    doc.setFontSize(13);
    doc.setTextColor(160, 160, 180);
    doc.text(subtitle, MARGIN + 12, 112);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 120);
    doc.text(`Total Questions: ${totalQuestions}`, MARGIN + 12, 125);
    doc.text(
      `Generated by HirePilot AI · ${new Date().toLocaleDateString("en-IN", {
        day: "numeric", month: "long", year: "numeric",
      })}`,
      MARGIN + 12,
      132
    );
  };

  // ── Header on content pages ──────────────────────────────────────────────────
  const addPageHeader = (sectionLabel: string, color: [number, number, number]) => {
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, PAGE_W, 16, "F");
    doc.setFillColor(...color);
    doc.rect(0, 14, PAGE_W, 1, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...color);
    doc.text("HirePilot AI", MARGIN, 10);
    doc.setTextColor(180, 180, 200);
    doc.text(sectionLabel, PAGE_W - MARGIN, 10, { align: "right" });
  };

  // ── Footer ───────────────────────────────────────────────────────────────────
  const addPageFooter = (pageNum: number) => {
    doc.setFillColor(15, 15, 25);
    doc.rect(0, PAGE_H - 12, PAGE_W, 12, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 120);
    doc.text(`Page ${pageNum}`, PAGE_W / 2, PAGE_H - 4, { align: "center" });
  };

  // ── Wrap text helper ─────────────────────────────────────────────────────────
  const wrapText = (text: string, maxWidth: number, fontSize: number): string[] => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth);
  };

  let pageNum = 1;

  // Add cover
  addCoverPage(
    section
      ? sectionsToExport[0].label
      : "Interview Questions",
    section ? "Section Export" : "Complete Question Bank"
  );
  addPageFooter(pageNum);

  // ── Content pages ────────────────────────────────────────────────────────────
  for (const meta of sectionsToExport) {
    const questions = normalise(result, meta.key);
    if (questions.length === 0) continue;

    // Section title page
    pageNum++;
    doc.addPage();
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");
    doc.setFillColor(...meta.color);
    doc.rect(MARGIN, 100, CONTENT_W, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text(meta.label, PAGE_W / 2, 95, { align: "center" });
    doc.setFontSize(11);
    doc.setTextColor(160, 160, 180);
    doc.text(`${questions.length} Questions`, PAGE_W / 2, 112, { align: "center" });
    addPageFooter(pageNum);

    // Questions
    let y = 24;

    const newPage = () => {
      addPageFooter(pageNum);
      pageNum++;
      doc.addPage();
      doc.setFillColor(15, 15, 25);
      doc.rect(0, 0, PAGE_W, PAGE_H, "F");
      addPageHeader(meta.label, meta.color);
      y = 24;
    };

    newPage(); // first content page for this section

    for (const q of questions) {
      // ── Question number badge ──────────────────────────────────────────────
      const badgeX = MARGIN;
      doc.setFillColor(...meta.color);
      doc.roundedRect(badgeX, y - 4, 8, 6, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(255, 255, 255);
      doc.text(`${q.index}`, badgeX + 4, y, { align: "center" });

      // ── Meta badge (difficulty etc.) ───────────────────────────────────────
      if (q.meta) {
        const metaLines = wrapText(q.meta, 80, 7.5);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(...meta.color);
        doc.text(metaLines[0], PAGE_W - MARGIN, y - 2, { align: "right" });
      }

      y += 4;

      // ── Question text ──────────────────────────────────────────────────────
      const qLines = wrapText(q.question, CONTENT_W - 2, 11);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(240, 240, 255);

      for (const line of qLines) {
        if (y > PAGE_H - 20) newPage();
        doc.text(line, MARGIN + 2, y);
        y += LINE_H;
      }

      y += 2;

      // ── Answer text ────────────────────────────────────────────────────────
      const aLines = wrapText(q.answer, CONTENT_W - 4, 9.5);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(170, 170, 190);

      for (const line of aLines) {
        if (y > PAGE_H - 20) newPage();
        doc.text(line, MARGIN + 4, y);
        y += LINE_H - 1;
      }

      // ── Divider ────────────────────────────────────────────────────────────
      y += 3;
      if (y > PAGE_H - 20) {
        newPage();
      } else {
        doc.setDrawColor(40, 40, 60);
        doc.line(MARGIN, y, PAGE_W - MARGIN, y);
        y += 5;
      }
    }

    addPageFooter(pageNum);
    isFirstPage = false;
  }

  void isFirstPage;

  const fileName = section
    ? `hirepilot-${section}-questions.pdf`
    : "hirepilot-all-interview-questions.pdf";

  doc.save(fileName);
}

// ─── DOCX ─────────────────────────────────────────────────────────────────────

export async function downloadAsDocx(
  result: InterviewResult,
  section?: Section
) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, ShadingType } =
    await import("docx");

  const sectionsToExport = section
    ? SECTIONS.filter((s) => s.key === section)
    : SECTIONS;

  const toHex = (rgb: [number, number, number]) =>
    rgb.map((v) => v.toString(16).padStart(2, "0")).join("").toUpperCase();

  const children: (typeof Paragraph.prototype)[] = [];

  // ── Cover heading ──────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      text: section
        ? sectionsToExport[0]?.label ?? "Interview Questions"
        : "Interview Questions — Complete Bank",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    })
  );

  const totalQ = sectionsToExport.reduce(
    (acc, s) => acc + normalise(result, s.key).length,
    0
  );

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
      children: [
        new TextRun({
          text: `Generated by HirePilot AI · ${totalQ} Questions · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
          color: "888888",
          size: 20,
          italics: true,
        }),
      ],
    })
  );

  for (const meta of sectionsToExport) {
    const questions = normalise(result, meta.key);
    if (questions.length === 0) continue;

    const hexColor = toHex(meta.color);

    // ── Section heading ────────────────────────────────────────────────────
    children.push(
      new Paragraph({
        text: meta.label,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 600, after: 200 },
        border: {
          bottom: { color: hexColor, size: 8, style: BorderStyle.SINGLE },
        },
      })
    );

    children.push(
      new Paragraph({
        spacing: { after: 300 },
        children: [
          new TextRun({
            text: `${questions.length} Questions`,
            color: hexColor,
            size: 20,
            bold: true,
          }),
        ],
      })
    );

    for (const q of questions) {
      // ── Question ──────────────────────────────────────────────────────────
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 80 },
          children: [
            new TextRun({
              text: `${q.index}. ${q.question}`,
              bold: true,
              size: 24,
            }),
          ],
        })
      );

      // ── Meta tag ──────────────────────────────────────────────────────────
      if (q.meta) {
        children.push(
          new Paragraph({
            spacing: { after: 80 },
            shading: { type: ShadingType.CLEAR, fill: "F3F4F6" },
            children: [
              new TextRun({
                text: `  ${q.meta}  `,
                color: hexColor,
                size: 16,
                italics: true,
                bold: true,
              }),
            ],
          })
        );
      }

      // ── Answer ────────────────────────────────────────────────────────────
      children.push(
        new Paragraph({
          spacing: { after: 240 },
          indent: { left: 360 },
          children: [
            new TextRun({
              text: q.answer,
              size: 20,
              color: "333333",
            }),
          ],
        })
      );

      // ── Divider ───────────────────────────────────────────────────────────
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          border: {
            bottom: { color: "DDDDDD", size: 4, style: BorderStyle.SINGLE },
          },
          children: [],
        })
      );
    }
  }

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22, color: "111827" },
          paragraph: { spacing: { line: 276 } },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 },
          },
        },
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = section
    ? `hirepilot-${section}-questions.docx`
    : "hirepilot-all-interview-questions.docx";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
